"""empty message

Revision ID: 006174f9988b
Revises: 26bc492acb7e
Create Date: 2021-03-17 16:35:25.640338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006174f9988b'
down_revision = '26bc492acb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('modify_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('modify_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
